build_dir = '/build_mex';
mex_dir = fullfile(pwd, build_dir);
srcs = {fullfile(mex_dir, 'lbp_mex.cpp'),...
    './src/hypothesis.cpp',...
    './src/lbp.cpp'
};
includes = {'./include',...
            mex_dir,...
            '/usr/include/eigen3'...
};
includes = cellfun(@(s) ['-I', s], includes,'UniformOutput', false);
eigen_path = '/usr/include/eigen3'; % Have no idea how to get around this...
mex('CXXFLAGS=$CXXFLAGS -std=c++17', srcs{:}, includes{:});
