load('./data/at612/priorLikelihood612.mat');

% gainMatPostC = [...
%             3.0, -inf,   -0.60, -inf, -inf, -inf, -inf;...
%             3.2, -inf, -inf,   -0.56, -inf, -inf, -inf;...
%            -3.0,     1.2, -inf, -inf,   -0.46, -inf, -inf;...
%         -inf,     3.0, -inf, -inf, -inf,   -0.62, -inf;...
%         -inf,    -0.4, -inf, -inf, -inf, -inf,   -0.55...
%     ];
hypos = [1, 2, 1, 3, 4, 5];
hyposCard = [2, 2, 1, 1];
probLogHypos = [log(0.5), log(0.5), log(0.5), log(0.5)];
clusters = [1, 2, 3, 4];
clustersCard = [2, 2];
num_tracks = 5;
num_measurements = 2;
gainMatPostC = rand(num_tracks + num_measurements, num_tracks + num_measurements);
gainMatPostC(1:num_tracks, :) = [...
            3.0, -inf,   -0.60, -inf, -inf, -inf, -inf;...
            3.2, -inf, -inf,   -0.56, -inf, -inf, -inf;...
           -3.0,     1.2, -inf, -inf,   -0.46, -inf, -inf;...
        -inf,     3.0, -inf, -inf, -inf,   -0.62, -inf;...
        -inf,    -0.4, -inf, -inf, -inf, -inf,   -0.55...
    ];

[o, l] = lbp_mex(gainMatPostC, num_tracks, num_measurements, hypos, hyposCard, probLogHypos, clusters, clustersCard);
