# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "cluster_tracks",
    "lbp_marginal",
    "lbp_single_cluster_bethe",
]

def cluster_tracks(clusters: numpy.typing.NDArray[numpy.uint64], clusters_card: numpy.typing.NDArray[numpy.uint64], hypos: numpy.typing.NDArray[numpy.uint64], hypos_card: numpy.typing.NDArray[numpy.uint64]) -> builtins.list[builtins.list[builtins.int]]:
    r"""
    Decode cluster membership from the four PMBM cloud arrays.
    
    Pass the raw arrays from ``priorLikelihood*.mat`` (1-based ids) as
    contiguous ``np.uint64`` arrays; they are borrowed zero-copy and cast to
    ``usize`` internally. Returns ``cluster -> sorted track numbers`` (cluster
    index 0-based).
    """

def lbp_marginal(llr: numpy.typing.NDArray[numpy.float64]) -> tuple[numpy.typing.NDArray[numpy.float64], builtins.float]: ...

def lbp_single_cluster_bethe(reward: typing.Sequence[builtins.float], rows: builtins.int, cols: builtins.int, hyps: typing.Sequence[tuple[typing.Sequence[builtins.int], builtins.float]], max_iters: builtins.int = 300) -> builtins.float:
    r"""
    Run single-cluster LBP+Bethe and return the normalization constant.
    
    Args:
      reward: row-major flat reward matrix ("edmund" layout), length rows*cols.
      rows, cols: its dimensions.
      hyps: list of (tracks, log_prob) prior hypotheses; `tracks` are 1-indexed
            local track ids as the C++ kernel expects.
      max_iters: LBP iteration cap.
    """

