//! Raw, unsafe FFI bindings to the dfg_da C API (`libdfg_da_c`).
//!
//! Generated by bindgen at build time (see `build.rs`); prefer the safe
//! wrappers in the `dfg-da` crate over using these directly.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
